microservice-chart:
  namespace: "printit"
  nameOverride: ""
  fullnameOverride: "print-payment-notice-service"
  image:
    repository: ghcr.io/pagopa/pagopa-print-payment-notice-service
    tag: "0.3.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 150
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 150
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "printit.itn.internal.dev.platform.pagopa.it"
    path: /pagopa-print-payment-notice-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: { }
    name: ""
  podAnnotations: { }
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      drop:
        - all
  tmpVolumeMount:
    create: true
    mounts:
      - name: temp
        mountPath: /temp
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'print-payment-notice-service' # required to show cloud role name in application insights
    ENV: 'azure-dev'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_SERVICE_NAME: 'print-payment-notice-service'
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    NOTICE_GENERATION_REST_ENDPOINT: "https://api.dev.platform.pagopa.it/print-payment-notice-generator/v1"
    KAFKA_BROKER: "pagopa-d-itn-core-evh-meucci.servicebus.windows.net:9093"
    KAFKA_NOTICE_GENERATION_TOPIC: 'pagopa-printit-evh'
    REST_CLIENT_LOGGER_LEVEL: 'FULL'
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'app-insight-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    MONGODB_CONNECTION_URI: 'notices-mongo-connection-string'
    TEMPLATE_STORAGE_CONN_STRING: 'templates-storage-account-connection-string'
    INSTITUTION_STORAGE_CONN_STRING: 'institutions-storage-account-connection_string'
    NOTICE_STORAGE_CONN_STRING: 'notices_storage-account-connection-string'
    KAFKA_SASL_JAAS_CONFIG: 'ehub-d-notice-jaas-config'
    AES_SECRET_KEY: 'aes-key'
    AES_SALT: 'aes-salt'
    NOTICE_GENERATION_SUBSCRIPTION_KEY: 'notice-generation-sub-key'
    NOTICE_STORAGE_ENDPOINT: 'notices-storage-account-blob-endpoint'
    NOTICE_STORAGE_CLIENT_ID: 'blob-storage-pdf-client-id'
    NOTICE_STORAGE_TENANT_ID: 'tenant-id'
    NOTICE_STORAGE_CLIENT_SECRET: 'pdf-generator-client-secret'
  keyvault:
    name: "pagopa-d-itn-printit-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: { }
  tolerations: [ ]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-print-payment-notice-service
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: { }
      envSecret: { }
