microservice-chart:
  namespace: "printit"
  nameOverride: ""
  fullnameOverride: "print-payment-notice-service"
  image:
    repository: ghcr.io/pagopa/pagopa-print-payment-notice-service
    tag: "0.0.2"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "printit.itn.internal.platform.pagopa.it"
    path: /pagopa-print-payment-notice-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: { }
    name: ""
  podAnnotations: { }
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'print-payment-notice-service' # required to show cloud role name in application insights
    ENV: 'azure-prod'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_SERVICE_NAME: 'print-payment-notice-service-otl'
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    KAFKA_BROKER: "pagopa-p-itn-core-evh-meucci.servicebus.windows.net:9092"
    KAFKA_NOTICE_GENERATION_TOPIC: pagopa-p-itn-printit-notice-evt-rx
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'app-insight-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    MONGODB_CONNECTION_URI: 'notices-mongo-connection-string'
    TEMPLATE_STORAGE_CONN_STRING: 'templates-storage-account-connection-string'
    KAFKA_SASL_JAAS_CONFIG: 'ehub-p-notice-jaas-config'
    AES_SECRET_KEY: 'aes-key'
    AES_SALT: 'aes-salt'
  keyvault:
    name: "pagopa-p-itn-printit-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: { }
  tolerations: [ ]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-print-payment-notice-service
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: { }
      envSecret: { }
